//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResxPropertiesBuilder.Cultures {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResxPropertiesBuilder.Cultures.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change the current culture used in the application.
        /// </summary>
        internal static string ChangeCultureComment {
            get {
                return ResourceManager.GetString("ChangeCultureComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This class was auto-generated by the ResxPropertiesBuilder.
        /// </summary>
        internal static string ClassComments1 {
            get {
                return ResourceManager.GetString("ClassComments1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на class via a tool like ResGen or Visual Studio..
        /// </summary>
        internal static string ClassComments2 {
            get {
                return ResourceManager.GetString("ClassComments2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To add or remove a member, edit your .ResX file then rerun ResGen.
        /// </summary>
        internal static string ClassComments3 {
            get {
                return ResourceManager.GetString("ClassComments3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на with the /str option, or rebuild your VS project..
        /// </summary>
        internal static string ClassComments4 {
            get {
                return ResourceManager.GetString("ClassComments4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на   A strongly-typed resource class, for looking up localized strings, etc..
        /// </summary>
        internal static string ClassDocComment {
            get {
                return ResourceManager.GetString("ClassDocComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrapper class of [Namespace].Properties.Resources  for access from XAML to the list of available languages and methods for changing the culture..
        /// </summary>
        internal static string ClassWPFComment {
            get {
                return ResourceManager.GetString("ClassWPFComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на   Overrides the current thread&apos;s CurrentUICulture property for all.
        /// </summary>
        internal static string CulturePropertyComment1 {
            get {
                return ResourceManager.GetString("CulturePropertyComment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на   resource lookups using this strongly typed resource class..
        /// </summary>
        internal static string CulturePropertyComment2 {
            get {
                return ResourceManager.GetString("CulturePropertyComment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Designer template file is Empty!.
        /// </summary>
        internal static string DesignerTemplateContentEmpty {
            get {
                return ResourceManager.GetString("DesignerTemplateContentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only fetch installed cultures once.
        /// </summary>
        internal static string FoundInstalledCulturesComment {
            get {
                return ResourceManager.GetString("FoundInstalledCulturesComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Resources ObjectDataProvider uses this method to get an instance of the [Namespace].[Properties].[Resources] class.
        /// </summary>
        internal static string GetResourceInstanceComment {
            get {
                return ResourceManager.GetString("GetResourceInstanceComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Identifier &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string InvalidIdentifier {
            get {
                return ResourceManager.GetString("InvalidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List of available cultures, enumerated at startup.
        /// </summary>
        internal static string ListOfAvailableCultures {
            get {
                return ResourceManager.GetString("ListOfAvailableCultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Returns a formatted localized string represented by the [name] parameter and the [args] parameter list.
        /// </summary>
        internal static string MethodGetStringWithNameArgsComment {
            get {
                return ResourceManager.GetString("MethodGetStringWithNameArgsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Searches for the localized given parameter [name].
        /// </summary>
        internal static string MethodGetStringWithNameComment {
            get {
                return ResourceManager.GetString("MethodGetStringWithNameComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Returns a formatted localized string represented by the [name] parameter, the [culture] and the [args] parameter list.
        /// </summary>
        internal static string MethodGetStringWithNameCultureArgsComment {
            get {
                return ResourceManager.GetString("MethodGetStringWithNameCultureArgsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Searches for the localized string represented by the [name] parameter and the [culture].
        /// </summary>
        internal static string MethodGetStringWithNameCultureComment {
            get {
                return ResourceManager.GetString("MethodGetStringWithNameCultureComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на When passing ResXDataNodes as the IDictionary values to StronglyTypedResourceBuilder.Create, the keys must match the corresponding values for ResXDataNode.Name.  Key name: &apos;{0}&apos;, ResXDataNode.Name: &apos;{1}&apos;..
        /// </summary>
        internal static string MismatchedResourceName {
            get {
                return ResourceManager.GetString("MismatchedResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на   Looks up a localized resource of type {0}..
        /// </summary>
        internal static string NonStringPropertyComment {
            get {
                return ResourceManager.GetString("NonStringPropertyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на   Looks up a localized resource of type {0} similar to {1}..
        /// </summary>
        internal static string NonStringPropertyDetailedComment {
            get {
                return ResourceManager.GetString("NonStringPropertyDetailedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на   Returns the cached ResourceManager instance used by this class..
        /// </summary>
        internal static string ResMgrPropertyComment {
            get {
                return ResourceManager.GetString("ResMgrPropertyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CultureResources ODP provides access to list of currently available cultures.
        /// </summary>
        internal static string ResourceDictionaryCultureResourcesListComment {
            get {
                return ResourceManager.GetString("ResourceDictionaryCultureResourcesListComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resources ODP contains the current instance of the [Namespace].[Properties].[Resources] class..
        /// </summary>
        internal static string ResourceDictionaryResourcesComment1 {
            get {
                return ResourceManager.GetString("ResourceDictionaryResourcesComment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Used in bindings to get localized strings and automatic updates when the culture is updated.
        /// </summary>
        internal static string ResourceDictionaryResourcesComment2 {
            get {
                return ResourceManager.GetString("ResourceDictionaryResourcesComment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на   Looks up a localized string similar to {0}..
        /// </summary>
        internal static string StringPropertyComment {
            get {
                return ResourceManager.GetString("StringPropertyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringPropertyTruncatedComment {
            get {
                return ResourceManager.GetString("StringPropertyTruncatedComment", resourceCulture);
            }
        }
    }
}
